---
- name: various conditions based on server facts
  hosts: kimsufi
  vars:
    username: cubic
  tasks:

    - name: install netstat
      when: ansible_distribution == "Ubuntu"
      apt: 
        name: netstat
        state: latest

    - name: install netstat
      when: ansible_distribution == "Centos"
      yum: 
        name: netstat
        state: latest
